### ISSUE TITLE
Unable to execute Processing's native methods from inside the callback methods of the anonymous classes.

### ISSUE THREAD

**Issue by Samuil9999** [ktbyte/processing-libraries#2]
It seems that it is impossible to execute not only the 'println()' method, but most of the other Processing's native methods from inside the anonymous class. Nonetheless, __*it is still possible to set and retrieve the values of the variables*__.

Here is an example from [KTGUI_Slider_KTByte_Example](https://github.com/ktbyte/processing-libraries/blob/master/GUI-library/KTGUI/KTGUI_Slider_KTByte_Example.pde). 
Inside the 'setup()' method we're creating the instance of the Slider class and then we're adding the callback methods inside the anonymous instance of the 'KTGUIEventAdapter':

```java
  slider = ktgui.createSlider(width/2 - 200, 150, 200*2, 40, 0, width - btn.width);
  slider.setTitle("The Slider");
  slider.addEventAdapters(new KTGUIEventAdapter() {
    ..............................
    ..............................
    // we can override only those callback methods which we really need
    void onMouseDragged() {
      slider.setTitle(slider.isPressed ? "Dragged" : "The Slider");
      if (slider.isPressed) {
        int sliderValue = (int)slider.getValue();
        btn.posx = sliderValue;
      }
    }
  }
  );
```
Now, if we'd use some of the Processing's internal methods, like for example 'map()' function, inside the 'onMouseDragged()' method, then we'll see that code after/including the line that uses the 'map()' method will not be executed.

```java
  slider = ktgui.createSlider(width/2 - 200, 150, 200*2, 40, 0, width - btn.width);
  slider.setTitle("The Slider");
  slider.addEventAdapters(new KTGUIEventAdapter() {
    ..............................
    ..............................
    // we can override only those callback methods which we really need
    void onMouseDragged() {
      slider.setTitle(slider.isPressed ? "Dragged" : "The Slider");
      if (slider.isPressed) {
        int sliderValue = (int)slider.getValue();
        //--------------------------------------------------------------------------------------------------//
        int mappedBtnPosition = (int) map(sliderValue, slider.sr, slider.er, 0, width - btn.width);
        btn.posx = mappedBtnPosition;
        //--------------------------------------------------------------------------------------------------//
      }
    }
  }
  );
```
I've tried to use several native Processing's methods, the results are all the same.

And another thing, if there is a lot of lines of code inside the callback method, then the code is executed only until (and excluding) the line with the native Processing method. All the rest of the lines are 'skipped'.

**Comment by Samuil9999** [comment]
I've just read again your message about the 'workaround' for the 'println()' method and I've tried to use the same approach for the 'map()' method. It worked!!! So, this 'workaround' can be used for other native Processing's methods.

```java
/**********************************************************************************************************************
 * This abstract class should be extended by the KTGUI components (controllers)
 *********************************************************************************************************************/
abstract class KTGUIEventAdapter {
  void onMousePressed() {
  }
  void onMouseReleased() {
  }
  void onMouseMoved() {
  }
  void onMouseDragged() {
  }
  void onKeyReleased() {
  }
  void onKeyPressed() {
  }
  void println(String text){
    PApplet.println(text);
  }
  float map(float value, float sin, float ein, float sout, float eout){
    return PApplet.map(value,  sin,  ein,  sout, eout);
  }
}
```

**Comment by Samuil9999** [comment]
To conclude,

The 'proxy' workaround allows calling the native Processing's method from inside the callback methods. 

In order to do that, one would need to:

1. Add the 'proxy' method to the 'KTGUIEventAdapter' class.
2. This method must have the same name as the native Processing's method that it proxies.
3. This method must have the same amount of arguments as the native Processing's method have. 
4. This method must have the same types of arguments as the native Processing's method have. 
5. This method must return the same type of value as the native Processing's method that it proxies.
6. Inside the added method one should add the call to the native Processing's method using the provided arguments.
7. If the native Processing's method returns some value, this value should be used to return the value from the 'proxy' method.

**Comment by ktbyte** [comment]
This is also found on the internal JIRA here: https://jira.ktbyte.com/browse/KTBYTEDEV-513

**Comment by Samuil9999** [comment]
I can't access the Jira thread. :(
